language: node_js
node_js:
  - "8.6"
sudo: false
# download test suite and run tests... submodule? meta testing project with
# all of the reference implementations?
script:
  - npm run test
notifications:
  email:
    on_success: change
    on_failure: change
